// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Silika.Data;

#nullable disable

namespace Silika.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220718173257_CreateLimbahB3")]
    partial class CreateLimbahB3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Silika.Entity.Bidang", b =>
                {
                    b.Property<Guid>("BidangID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KepalaBidang")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.Property<string>("NamaBidang")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BidangID");

                    b.ToTable("Bidang");
                });

            modelBuilder.Entity("Silika.Entity.JenisKendaraan", b =>
                {
                    b.Property<int>("JenisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JenisID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KodeJenis")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NamaJenis")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("JenisID");

                    b.ToTable("JenisKendaraan");
                });

            modelBuilder.Entity("Silika.Entity.JenisPencemaran", b =>
                {
                    b.Property<int>("JenisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JenisID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NamaJenis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("JenisID");

                    b.ToTable("JenisPencemaran");
                });

            modelBuilder.Entity("Silika.Entity.JenisTps", b =>
                {
                    b.Property<int>("JenisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JenisID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NamaJenis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("JenisID");

                    b.ToTable("JenisTps");
                });

            modelBuilder.Entity("Silika.Entity.JenisWr", b =>
                {
                    b.Property<int>("JenisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JenisID"));

                    b.Property<string>("NamaJenis")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.Property<string>("NoRekening")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("JenisID");

                    b.ToTable("JenisWr");
                });

            modelBuilder.Entity("Silika.Entity.Kabupaten", b =>
                {
                    b.Property<string>("KabupatenID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsKota")
                        .HasColumnType("boolean");

                    b.Property<string>("Latitude")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Longitude")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("NamaKabupaten")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ProvinsiID")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("KabupatenID");

                    b.HasIndex("ProvinsiID");

                    b.ToTable("Kabupaten");
                });

            modelBuilder.Entity("Silika.Entity.Kecamatan", b =>
                {
                    b.Property<string>("KecamatanID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("KabupatenID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Latitude")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Longitude")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("NamaKecamatan")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("KecamatanID");

                    b.HasIndex("KabupatenID");

                    b.ToTable("Kecamatan");
                });

            modelBuilder.Entity("Silika.Entity.Kelurahan", b =>
                {
                    b.Property<string>("KelurahanID")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("KecamatanID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Latitude")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Longitude")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("NamaKelurahan")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("KelurahanID");

                    b.HasIndex("KecamatanID");

                    b.ToTable("Kelurahan");
                });

            modelBuilder.Entity("Silika.Entity.Kendaraan", b =>
                {
                    b.Property<int>("KendaraanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KendaraanId"));

                    b.Property<Guid?>("BidangAsalId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BidangPenugasanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("Fungsi")
                        .HasColumnType("smallint");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("JenisKendaraanId")
                        .HasColumnType("integer");

                    b.Property<string>("KabupatenAsalId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("KabupatenPenugasanId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("KecamatanAsalId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("KecamatanPenugasanId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<double?>("KonsumsiBBM")
                        .HasColumnType("double precision");

                    b.Property<int?>("MerkKendaraanId")
                        .HasColumnType("integer");

                    b.Property<string>("NoPintu")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("NoPolisi")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("NoRangka")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TahunPengadaan")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int?>("TipeKendaraanId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("KendaraanId");

                    b.HasIndex("BidangAsalId");

                    b.HasIndex("BidangPenugasanId");

                    b.HasIndex("JenisKendaraanId");

                    b.HasIndex("KabupatenAsalId");

                    b.HasIndex("KabupatenPenugasanId");

                    b.HasIndex("KecamatanAsalId");

                    b.HasIndex("KecamatanPenugasanId");

                    b.HasIndex("MerkKendaraanId");

                    b.HasIndex("TipeKendaraanId");

                    b.ToTable("Kendaraan");
                });

            modelBuilder.Entity("Silika.Entity.LimbahB3", b =>
                {
                    b.Property<int>("LimbahB3Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LimbahB3Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KodeLimbah")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("NamaLimbah")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LimbahB3Id");

                    b.ToTable("LimbahB3");
                });

            modelBuilder.Entity("Silika.Entity.MerkKendaraan", b =>
                {
                    b.Property<int>("MerkKendaraanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MerkKendaraanId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KodeMerk")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NamaMerk")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MerkKendaraanId");

                    b.ToTable("MerkKendaraan");
                });

            modelBuilder.Entity("Silika.Entity.NilaiPencemaran", b =>
                {
                    b.Property<int>("NilaiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NilaiID"));

                    b.Property<short>("Akhir")
                        .HasColumnType("smallint");

                    b.Property<short>("Awal")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NamaNilai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NilaiID");

                    b.ToTable("NilaiPencemaran");
                });

            modelBuilder.Entity("Silika.Entity.Pegawai", b =>
                {
                    b.Property<int>("PegawaiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PegawaiId"));

                    b.Property<Guid?>("BidangId")
                        .HasColumnType("uuid");

                    b.Property<string>("Catatan")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("KabupatenId")
                        .HasColumnType("character varying(10)");

                    b.Property<string>("KecamatanId")
                        .HasColumnType("character varying(10)");

                    b.Property<string>("KelurahanId")
                        .HasColumnType("character varying(15)");

                    b.Property<string>("NIK")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("NamaPegawai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NoHP")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("StatusAktif")
                        .HasColumnType("boolean");

                    b.Property<short?>("TahunMasuk")
                        .HasColumnType("smallint");

                    b.Property<DateOnly>("TglLahir")
                        .HasColumnType("date");

                    b.Property<int>("TipePegawaiId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PegawaiId");

                    b.HasIndex("BidangId");

                    b.HasIndex("KabupatenId");

                    b.HasIndex("KecamatanId");

                    b.HasIndex("KelurahanId");

                    b.HasIndex("TipePegawaiId");

                    b.ToTable("Pegawai");
                });

            modelBuilder.Entity("Silika.Entity.Penugasan", b =>
                {
                    b.Property<int>("PenugasanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PenugasanId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NamaPenugasan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("PenugasanId");

                    b.ToTable("Penugasan");
                });

            modelBuilder.Entity("Silika.Entity.Provinsi", b =>
                {
                    b.Property<string>("ProvinsiID")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("HcKey")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("KodeNegara")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Latitude")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Longitude")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("NamaProvinsi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ProvinsiID");

                    b.ToTable("Provinsi");
                });

            modelBuilder.Entity("Silika.Entity.StatusLahan", b =>
                {
                    b.Property<int>("StatusLahanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusLahanId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NamaStatus")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StatusLahanId");

                    b.ToTable("StatusLahan");
                });

            modelBuilder.Entity("Silika.Entity.TipeKendaraan", b =>
                {
                    b.Property<int>("TipeKendaraanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipeKendaraanId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MerkKendaraanId")
                        .HasColumnType("integer");

                    b.Property<string>("NamaTipe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TipeKendaraanId");

                    b.HasIndex("MerkKendaraanId");

                    b.ToTable("TipeKendaraan");
                });

            modelBuilder.Entity("Silika.Entity.TipePegawai", b =>
                {
                    b.Property<int>("TipePegawaiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TipePegawaiId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NamaTipe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TipePegawaiId");

                    b.ToTable("TipePegawai");
                });

            modelBuilder.Entity("Silika.Entity.Tps", b =>
                {
                    b.Property<int>("TpsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TpsId"));

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("JenisTpsId")
                        .HasColumnType("integer");

                    b.Property<string>("KelurahanID")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("text");

                    b.Property<string>("KodePos")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Latitude")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Longitude")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NamaTps")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("StatusLahanId")
                        .HasColumnType("integer");

                    b.Property<string>("TpsCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TpsId");

                    b.HasIndex("JenisTpsId");

                    b.HasIndex("KelurahanID");

                    b.HasIndex("StatusLahanId");

                    b.ToTable("Tps");
                });

            modelBuilder.Entity("Silika.Entity.Kabupaten", b =>
                {
                    b.HasOne("Silika.Entity.Provinsi", "Provinsi")
                        .WithMany("Kabupatens")
                        .HasForeignKey("ProvinsiID");

                    b.Navigation("Provinsi");
                });

            modelBuilder.Entity("Silika.Entity.Kecamatan", b =>
                {
                    b.HasOne("Silika.Entity.Kabupaten", "Kabupaten")
                        .WithMany("Kecamatans")
                        .HasForeignKey("KabupatenID");

                    b.Navigation("Kabupaten");
                });

            modelBuilder.Entity("Silika.Entity.Kelurahan", b =>
                {
                    b.HasOne("Silika.Entity.Kecamatan", "Kecamatan")
                        .WithMany("Kelurahans")
                        .HasForeignKey("KecamatanID");

                    b.Navigation("Kecamatan");
                });

            modelBuilder.Entity("Silika.Entity.Kendaraan", b =>
                {
                    b.HasOne("Silika.Entity.Bidang", "BidangAsal")
                        .WithMany("KendaraanAsal")
                        .HasForeignKey("BidangAsalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Silika.Entity.Bidang", "BidangPenugasan")
                        .WithMany("KendaraanPenugasan")
                        .HasForeignKey("BidangPenugasanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Silika.Entity.JenisKendaraan", "JenisKendaraan")
                        .WithMany("Kendaraans")
                        .HasForeignKey("JenisKendaraanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Silika.Entity.Kabupaten", "KabupatenAsal")
                        .WithMany("KendaraanAsal")
                        .HasForeignKey("KabupatenAsalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Silika.Entity.Kabupaten", "KabupatenPenugasan")
                        .WithMany("KendaraanPenugasan")
                        .HasForeignKey("KabupatenPenugasanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Silika.Entity.Kecamatan", "KecamatanAsal")
                        .WithMany("KendaraanAsal")
                        .HasForeignKey("KecamatanAsalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Silika.Entity.Kecamatan", "KecamatanPenugasan")
                        .WithMany("KendaraanPenugasan")
                        .HasForeignKey("KecamatanPenugasanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Silika.Entity.MerkKendaraan", "MerkKendaraan")
                        .WithMany("Kendaraans")
                        .HasForeignKey("MerkKendaraanId");

                    b.HasOne("Silika.Entity.TipeKendaraan", "TipeKendaraan")
                        .WithMany("Kendaraans")
                        .HasForeignKey("TipeKendaraanId");

                    b.Navigation("BidangAsal");

                    b.Navigation("BidangPenugasan");

                    b.Navigation("JenisKendaraan");

                    b.Navigation("KabupatenAsal");

                    b.Navigation("KabupatenPenugasan");

                    b.Navigation("KecamatanAsal");

                    b.Navigation("KecamatanPenugasan");

                    b.Navigation("MerkKendaraan");

                    b.Navigation("TipeKendaraan");
                });

            modelBuilder.Entity("Silika.Entity.Pegawai", b =>
                {
                    b.HasOne("Silika.Entity.Bidang", "Bidang")
                        .WithMany("Pegawais")
                        .HasForeignKey("BidangId");

                    b.HasOne("Silika.Entity.Kabupaten", "Kabupaten")
                        .WithMany("Pegawais")
                        .HasForeignKey("KabupatenId");

                    b.HasOne("Silika.Entity.Kecamatan", "Kecamatan")
                        .WithMany("Pegawais")
                        .HasForeignKey("KecamatanId");

                    b.HasOne("Silika.Entity.Kelurahan", "Kelurahan")
                        .WithMany("Pegawais")
                        .HasForeignKey("KelurahanId");

                    b.HasOne("Silika.Entity.TipePegawai", "TipePegawai")
                        .WithMany("Pegawais")
                        .HasForeignKey("TipePegawaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bidang");

                    b.Navigation("Kabupaten");

                    b.Navigation("Kecamatan");

                    b.Navigation("Kelurahan");

                    b.Navigation("TipePegawai");
                });

            modelBuilder.Entity("Silika.Entity.TipeKendaraan", b =>
                {
                    b.HasOne("Silika.Entity.MerkKendaraan", "MerkKendaraan")
                        .WithMany("TipeKendaraans")
                        .HasForeignKey("MerkKendaraanId");

                    b.Navigation("MerkKendaraan");
                });

            modelBuilder.Entity("Silika.Entity.Tps", b =>
                {
                    b.HasOne("Silika.Entity.JenisTps", "JenisTps")
                        .WithMany("Tps")
                        .HasForeignKey("JenisTpsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Silika.Entity.Kelurahan", "Kelurahan")
                        .WithMany("Tps")
                        .HasForeignKey("KelurahanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Silika.Entity.StatusLahan", "StatusLahan")
                        .WithMany()
                        .HasForeignKey("StatusLahanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JenisTps");

                    b.Navigation("Kelurahan");

                    b.Navigation("StatusLahan");
                });

            modelBuilder.Entity("Silika.Entity.Bidang", b =>
                {
                    b.Navigation("KendaraanAsal");

                    b.Navigation("KendaraanPenugasan");

                    b.Navigation("Pegawais");
                });

            modelBuilder.Entity("Silika.Entity.JenisKendaraan", b =>
                {
                    b.Navigation("Kendaraans");
                });

            modelBuilder.Entity("Silika.Entity.JenisTps", b =>
                {
                    b.Navigation("Tps");
                });

            modelBuilder.Entity("Silika.Entity.Kabupaten", b =>
                {
                    b.Navigation("Kecamatans");

                    b.Navigation("KendaraanAsal");

                    b.Navigation("KendaraanPenugasan");

                    b.Navigation("Pegawais");
                });

            modelBuilder.Entity("Silika.Entity.Kecamatan", b =>
                {
                    b.Navigation("Kelurahans");

                    b.Navigation("KendaraanAsal");

                    b.Navigation("KendaraanPenugasan");

                    b.Navigation("Pegawais");
                });

            modelBuilder.Entity("Silika.Entity.Kelurahan", b =>
                {
                    b.Navigation("Pegawais");

                    b.Navigation("Tps");
                });

            modelBuilder.Entity("Silika.Entity.MerkKendaraan", b =>
                {
                    b.Navigation("Kendaraans");

                    b.Navigation("TipeKendaraans");
                });

            modelBuilder.Entity("Silika.Entity.Provinsi", b =>
                {
                    b.Navigation("Kabupatens");
                });

            modelBuilder.Entity("Silika.Entity.TipeKendaraan", b =>
                {
                    b.Navigation("Kendaraans");
                });

            modelBuilder.Entity("Silika.Entity.TipePegawai", b =>
                {
                    b.Navigation("Pegawais");
                });
#pragma warning restore 612, 618
        }
    }
}
